/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AppMode } from '../types';

// 2026-09-18 — Apresentações de voz (ícone «Microfone» do cabeçalho) revistas
// página a página contra a interface actual: removidas páginas que já não
// existem (Pagamentos, Pasta Digital, «Documentos» do cidadão), acrescentadas
// as páginas novas (Vídeo-Atendimento, Inquéritos, Ocorrências, Livro de
// Reclamações, Directório de Órgãos, Solicitar Documento, Histórico e
// Notificações da instituição, Sondagens, Emissão Documental) e actualizado o
// texto das restantes para descrever apenas o que cada ecrã mostra hoje.

const INTRO = "Seja muito bem-vindo ao Correio Digital Angola. Uma plataforma de correspondência Nacional com o objetivo de unir as Instituições à população. ";

const VIDEO_ATENDIMENTO_CIDADAO = INTRO + "Está na página Vídeo-Atendimento. Aqui encontra os atendimentos por vídeo marcados pelas instituições consigo. A página está organizada em quatro separadores: Agenda, com a lista de atendimentos disponíveis e a data e hora de cada um; Histórico, com as sessões já realizadas; Calendário, com a vista mensal das marcações; e Ajuda. Na hora marcada, seleccione o atendimento na Agenda e carregue em Entrar para abrir a sala de vídeo, com áudio e imagem em tempo real, directamente no navegador, sem instalar aplicações. Pode também eliminar um atendimento da sua área; a instituição é notificada. ";

const VIDEO_ATENDIMENTO_INSTITUICAO = INTRO + "Está na página Vídeo-Atendimento da sua instituição. Aqui pode agendar atendimentos por vídeo com cidadãos e conduzi-los. Use o botão Agendar Vídeo-Atendimento e indique o número de Bilhete de Identidade do cidadão, o assunto, a data e a hora. O cidadão recebe uma notificação oficial e vê a sessão na página dele. Os separadores Agenda, Histórico, Calendário e Ajuda organizam as sessões marcadas, as já realizadas e a vista mensal. No horário marcado, ambos entram na mesma sala de vídeo, em tempo real, com áudio e imagem, sem instalar aplicações. ";

const HISTORICO_COMUM = "A página divide-se em três blocos: Linha Temporal Recente, com os últimos eventos ordenados por data; Estado dos Fluxos, com os indicadores de correspondências pendentes, solicitações em aberto, notificações e eventos auditáveis; e Atalhos de Continuidade, com botões para retomar rapidamente as áreas onde tem trabalho pendente. ";

const NOTIFICACOES_COMUM = INTRO + "Está no Centro de Notificações. Os avisos estão agrupados em três secções: Alertas Prioritários, que exigem atenção imediata; Actualizações Concluídas, com confirmações de emissão ou entrega; e Informações do Sistema, com eventos operacionais. Cada notificação pode ser aberta para consultar o detalhe e, quando aplicável, ir directamente à correspondência ou processo relacionado. O botão Ver Histórico leva à linha temporal completa da conta. ";

export const PAGE_PRESENTATIONS: Record<AppMode, Record<string, string>> = {
  user: {
    home: INTRO + "Está no Painel, a sua página inicial. No topo, um destaque com as novidades da plataforma. A seguir, dois cartões: o seu ID Digital, com o estado de verificação do seu Bilhete de Identidade, e as Novas Mensagens, com o número de correspondências ainda não lidas. Depois encontra cinco atalhos: Vídeo-Atendimento, Inquéritos, Ocorrências Locais, Denuncia e Livro de Reclamações, cada um com o contador de novidades por ver. Mais abaixo, a faixa de Instituições Conectadas e, por fim, as suas correspondências organizadas em três colunas: Não Lidas, Lidas e Enviadas. Basta clicar numa mensagem para a abrir. O menu lateral dá acesso ao Correio, aos Contactos e ao Perfil. ",
    correspondencias: INTRO + "Está na página Correio, a sua caixa de correspondência oficial com as instituições do Estado. As mensagens estão organizadas em quatro separadores: Lidas, Não Lidas, Enviadas e Eliminadas. A tabela mostra, para cada correspondência, o órgão emissor, o assunto, um resumo do conteúdo, a data de expiração, a hora e data de envio, a prioridade e as acções disponíveis. Com o botão Nova Mensagem pode escrever a uma instituição: escolhe entre Mensagem Normal e Reclamação, indica a instituição destinatária, o título e o conteúdo, pode juntar anexos, definir uma data de expiração e pedir ajuda da inteligência artificial para rever o texto. Ao abrir uma mensagem recebida, pode responder, ver a localização do órgão no mapa, validar o código QR e acompanhar o estado de entrega e leitura. ",
    contatos: INTRO + "Está na página Contactos, o seu Círculo de Confiança. Tem dois separadores. Contactos Pessoais reúne as pessoas da sua rede, com filtros Todos, Emergência e Normal; para cada contacto vê o nome e a relação, o Bilhete de Identidade, o vínculo e o estado da autorização. Com o botão Adicionar regista um novo contacto com o nome completo, o número de Bilhete de Identidade, o grau de parentesco, o telefone, e opcionalmente WhatsApp e e-mail, escolhendo se é um contacto Normal ou de Emergência. Para completar o perfil precisa de, pelo menos, dois contactos de Emergência com telefone válido: é esta rede que as instituições usam para chegar à sua família em situações críticas. O separador Contactos Institucionais mostra as instituições que adicionou. ",
    contactos: INTRO + "Está na página Contactos, o seu Círculo de Confiança. Tem dois separadores. Contactos Pessoais reúne as pessoas da sua rede, com filtros Todos, Emergência e Normal; para cada contacto vê o nome e a relação, o Bilhete de Identidade, o vínculo e o estado da autorização. Com o botão Adicionar regista um novo contacto com o nome completo, o número de Bilhete de Identidade, o grau de parentesco, o telefone, e opcionalmente WhatsApp e e-mail, escolhendo se é um contacto Normal ou de Emergência. Para completar o perfil precisa de, pelo menos, dois contactos de Emergência com telefone válido: é esta rede que as instituições usam para chegar à sua família em situações críticas. O separador Contactos Institucionais mostra as instituições que adicionou. ",
    perfil: INTRO + "Está na página Perfil, a sua conta de cidadão. No cartão principal encontra o seu nome, o Bilhete de Identidade e o nível de verificação, com os botões Editar Perfil, Configuração e Alterar Foto. A seguir vê as Estatísticas da Conta, as Informações Pessoais e a Actividade Recente, com o botão Ver Toda a Actividade. Na secção Segurança pode alterar a palavra-passe, activar a autenticação em dois factores, gerir as sessões activas, ver os dispositivos ligados e registar a sua face para o acesso por reconhecimento facial. A secção Contactos de Emergência mostra se a sua rede está completa e liga à página Contactos. Em Configuração ajusta o idioma, os canais de notificação, a privacidade e a biometria. ",
    "qr-code": INTRO + "Está na página QR Code, a sua Carteira Digital. Aqui ficam os documentos digitais validados em seu nome, cada um com o respectivo código QR e validade jurídica. Enquanto não tiver documentos, a carteira aparece vazia. Com o botão Solicitar Documento inicia um pedido a uma instituição; os botões Ver Histórico, Notificações e Ver Solicitações permitem acompanhar o que já pediu. A caixa de pesquisa procura dentro da sua carteira. ",
    "solicitar-documento": INTRO + "Está na página Solicitar Documento Digital. Primeiro escolhe qual o acto governamental que pretende requerer, entre as opções disponíveis: Bilhete de Identidade Digital, pelo SME; Licença ou Carta de Condução, pela Polícia Nacional; Declarações oficiais, pela Conservatória; e Documento Fiscal, pela AGT. Depois preenche os Dados de Concessão: a modalidade específica do documento, o nome completo do titular, o código de identificação, a finalidade e a prioridade processual, Alta ou Média. O botão Preencher com os Meus Dados usa a informação do seu perfil. No passo Seguinte junta os anexos necessários e submete o pedido, que pode depois acompanhar na Carteira Digital e nas notificações. ",
    historico: INTRO + "Está na página Histórico do Cidadão, a linha do tempo da sua actividade na plataforma: correspondências abertas e enviadas, documentos, solicitações e notificações. " + HISTORICO_COMUM,
    notificacoes: NOTIFICACOES_COMUM,
    "video-atendimento": VIDEO_ATENDIMENTO_CIDADAO,
    inqueritos: INTRO + "Está na página Inquéritos. Aqui encontra os inquéritos e sondagens que as instituições lhe enviaram, organizados em dois separadores: Normal, com sondagens de pergunta e opções de resposta, e IA, com inquéritos conversacionais em que a inteligência artificial faz as perguntas por texto ou por voz e recolhe as suas respostas. Clique num inquérito para o abrir e responder. Cada resposta é registada de forma segura e associada à sua conta. ",
    ocorrencias: INTRO + "Está na página Ocorrências Locais. Aqui pode comunicar problemas do seu bairro ou localidade às instituições responsáveis e acompanhar a sua resolução. Com o botão Registar Ocorrência indica o que aconteceu, escolhe a categoria, como iluminação pública, estradas e vias, água, saneamento, resíduos, infraestruturas públicas ou árvores e espaços verdes, define a localização, de forma automática por GPS ou manualmente por província, município e bairro, escolhe a instituição destinatária e pode juntar fotografias. Os separadores Ocorrências e Notificações mostram a lista das suas participações e as actualizações recebidas. Ao abrir uma ocorrência acompanha o estado, desde Submetida e Recebida, passando por Em Análise e Em Resolução, até Resolvida e Encerrada, com o histórico de comunicações da instituição. ",
    denuncias: INTRO + "Está na página Livro de Reclamações. Aqui consulta as reclamações que enviou às instituições e acompanha o respectivo processo. Com o botão Criar Denúncia abre uma nova reclamação, que segue marcada como tal para a instituição visada. Ao abrir uma reclamação vê o cronograma do processo em cinco fases: Registada, Recebida, Em Análise, Respondida e Encerrada, além das comunicações trocadas. A caixa de pesquisa procura por assunto ou número. ",
    "directorio-orgaos": INTRO + "Está no Directório de Órgãos. Aqui consulta, por categoria, os órgãos do Estado angolano: Presidência da República, Ministérios, Justiça, Registos e Notariado, Administração Tributária e Finanças, Bancos, Seguradoras, Energia e Águas, Saúde, Educação, Transportes, Administração Provincial e Local, entre outras. Abra uma categoria para ver as entidades e, em cada ficha, os contactos, o endereço, a localização no mapa e a opção de enviar mensagem. ",
    "nova-denuncia": INTRO + "Está na página Denuncia. Aqui consulta as denuncias que enviou às instituições e acompanha o respectivo processo. Com o botão Criar Denuncia abre uma nova denuncia, que segue marcada como tal para a instituição visada. Ao abrir uma denuncia vê o cronograma do processo em cinco fases: Registada, Recebida, Em Análise, Respondida e Encerrada, além das comunicações trocadas. A caixa de pesquisa procura por assunto ou número. ",
  },
  institution: {
    home: INTRO + "Está no Painel da sua instituição. No topo, um destaque com as novidades da plataforma. A seguir, os cartões de identificação institucional e de Novas Mensagens, com o número de correspondências por ler. Depois, cinco atalhos: Vídeo-Atendimento, Inquéritos, Ocorrências Recebidas, Denuncia e Livro de Reclamações, cada um com o contador de novidades. Mais abaixo, a faixa de Instituições Conectadas e as correspondências organizadas em três colunas: Não Lidas, Lidas e Enviadas. Clique numa mensagem para a abrir. O menu lateral dá acesso ao Correio, à Equipa, ao QR Code, à IA e ao Perfil. ",
    correspondencias: INTRO + "Está na página Correio, o expediente de entrada da sua instituição. As correspondências estão organizadas em quatro separadores: Lidas, Não Lidas, Enviadas e Eliminadas. A tabela mostra o cidadão requerente, o assunto, um resumo do conteúdo, a data de expiração, a hora e data, a prioridade e as acções. Com o botão Nova Mensagem envia correspondência a um cidadão, identificado pelo Bilhete de Identidade, ou a outra instituição: escolhe entre Mensagem Normal e Mensagem de Emergência, esta última com difusão prioritária para a rede de contactos familiares do cidadão. Pode juntar anexos, definir a data de expiração, pedir à inteligência artificial que reveja o texto e, com Criar Inquérito, incluir uma sondagem normal ou um inquérito conduzido por IA. O botão Validação QR abre o leitor de códigos. Ao abrir uma mensagem pode responder, ver a localização no mapa e acompanhar a entrega e a leitura. ",
    "gov-contatos": INTRO + "Está na página Equipa, a gestão dos colaboradores da sua instituição. O Quadro da Equipa lista cada membro com o seu perfil funcional, os contactos e o estado de acesso. Com o botão Adicionar à Equipa regista um novo colaborador, com os dados de identificação, a função e as permissões. Pode editar ou remover membros, garantindo que apenas pessoas autorizadas usam a plataforma em nome da instituição. ",
    "inst-qrcode": INTRO + "Está na página QR Code, o leitor e gerador de códigos de correspondência. Tem três separadores: Ler QR Code, Gerar QR Code e Histórico. Para ler, escolha o método: Webcam ou Câmara do telemóvel, Leitor USB profissional, carregamento de Ficheiro ou Colar Texto. Ao ler um código, a plataforma localiza o documento ou correspondência, confirma a autenticidade e a assinatura digital e regista a leitura, para auditoria. Em Gerar QR Code cria códigos para documentos da sua instituição. O Histórico guarda todas as validações efectuadas. ",
    "inst-ai-assistant": INTRO + "Está na página IA, o assistente de inteligência artificial da sua instituição. Em Configuração define o nome do assistente, a descrição e instrução do sistema, o modelo de IA e a temperatura, e guarda com Guardar Configuração. Em Base de Conhecimento adiciona documentos e informação sobre os serviços da instituição, para que a IA responda aos cidadãos com dados actualizados. Em Chat Teste experimenta o assistente antes de o disponibilizar, e o botão Pré-visualizar Assistente mostra como o cidadão o verá. O Histórico regista as conversas atendidas. ",
    perfil: INTRO + "Está na página Perfil da sua conta institucional. No cartão principal encontra a identificação do agente e da instituição, com os botões Editar Perfil e Alterar Foto. A seguir vê as Informações da Conta, a Segurança da Conta, com Alterar Senha e autenticação em dois factores e o registo da face para acesso facial, os Dispositivos ligados, com Gerir Dispositivos, as Preferências, com Gerir Preferências, e a Actividade Recente na Conta, com o botão Ver Toda a Actividade. ",
    documentos: INTRO + "Está na página Expedientes e Arquivos, o repositório de documentos da sua instituição. A tabela do expediente de entrada mostra, para cada documento, o cidadão requerente, o tipo e assunto, o conteúdo, o prazo de validade, a data de emissão, o nível de restrição e as acções, incluindo Analisar Documento. Com Submeter Documento envia um documento oficial a um cidadão. Os botões Notificações e Validação QR dão acesso aos avisos e ao leitor de códigos. ",
    "qr-code": INTRO + "Está na página Controle de Emissão Documental. Aqui acompanha os documentos emitidos pela sua instituição, filtrados por Todos, Emitidos, Pendentes e Rejeitados. Os botões Ver Histórico, Notificações e Ver Métricas de Emissão dão acesso ao registo e aos indicadores de emissão. ",
    historico: INTRO + "Está na página Histórico Institucional, a linha do tempo da actividade da sua instituição na plataforma: correspondências recebidas e enviadas, documentos e notificações. " + HISTORICO_COMUM,
    notificacoes: NOTIFICACOES_COMUM,
    "video-atendimento": VIDEO_ATENDIMENTO_INSTITUICAO,
    inqueritos: INTRO + "Está na página Inquéritos da sua instituição. Aqui consulta os inquéritos que criou e os respectivos resultados, em dois separadores: Normal, com as sondagens de pergunta e opções, e IA, com os inquéritos conversacionais conduzidos pela inteligência artificial. Cada inquérito mostra a data, o número de perguntas e de destinatários; ao abrir vê as respostas recolhidas. Para criar um novo, use Criar Inquéritos, que o leva ao compositor do Correio. ",
    sondagens: INTRO + "Está na página Sondagens. Aqui consulta as sondagens normais criadas pela sua instituição e os seus resultados: a pergunta, as opções e a contagem de respostas dos cidadãos. Para criar uma nova sondagem, use Criar Inquérito na página Correio. ",
    ocorrencias: INTRO + "Está na página Ocorrências Recebidas. Aqui gere as ocorrências que os cidadãos comunicaram à sua instituição: problemas de iluminação pública, estradas, água, saneamento, resíduos, infraestruturas e espaços verdes. Os contadores Recebidas, Em Análise e Em Resolução resumem a fila de trabalho, e pode procurar por texto ou por bairro e localidade. Ao abrir uma ocorrência vê a descrição, a localização no mapa, as fotografias e o histórico; pode actualizar o estado, comunicar com o cidadão, pedir informação adicional ou encaminhar para outra instituição, até à resolução e encerramento. ",
    denuncias: INTRO + "Está na página Livro de Reclamações. Aqui consulta as reclamações dirigidas à sua instituição e acompanha o respectivo processo. Ao abrir uma reclamação vê o cronograma em cinco fases: Registada, Recebida, Em Análise, Respondida e Encerrada. Avance cada fase à medida que trata o processo e responda ao cidadão pela correspondência associada. A caixa de pesquisa procura por assunto ou número. ",
    "nova-denuncia": INTRO + "Está na página Denuncia. Aqui consulta as denuncias dirigidas à sua instituição e acompanha o respectivo processo. Ao abrir uma denuncia vê o cronograma em cinco fases: Registada, Recebida, Em Análise, Respondida e Encerrada. Avance cada fase à medida que trata o processo e responda ao cidadão pela correspondência associada. A caixa de pesquisa procura por assunto ou número. "
  },
  admin: {
    "gov-dashboard": INTRO + "Está no Painel Nacional de Correspondência, o centro de operações da Administração Central. No Resumo Geral vê os indicadores consolidados do sistema: cidadãos, instituições, correspondências e documentos. A secção Auditoria de Vídeo-Atendimento Integrado mostra o histórico geral de sessões por instituição e o registo de auditoria do atendimento. Mais abaixo, o Painel Analítico, os Serviços Inteligentes e a Actividade Recente e Estado, que pode expandir com os botões Mostrar. Os atalhos Ver Histórico, Notificações e Emissão Documental levam às restantes áreas. ",
    "gov-interoperabilidade": INTRO + "Está na página Instituições, a Gestão Institucional. Em Solicitações de Registo de Instituições analisa e aprova os pedidos de adesão de novas entidades. O Painel Geral de Filtros e Busca permite localizar instituições por sigla ou nome, município e categoria, e filtrar por Todas, Activas e Inactivas; a tabela mostra o nome, a sigla, o tipo, a província, o responsável, a data e o estado. Com Registar Instituição cria uma nova entidade no ecossistema, e o botão Actualizar recarrega a lista. ",
    "gov-correspondencias": INTRO + "Está na página Correspondências Digitais, o registo consolidado de todas as correspondências do sistema. A Pesquisa Avançada e os Filtros de Auditoria permitem procurar por remetente, destinatário, assunto e categoria de matéria, com filtros geográficos e a opção de ver apenas atrasados. Os contadores Expediente, Enviadas, Recebidas, Em Análise, Respondidas, Arquivadas e Canceladas resumem o tráfego. Para cada correspondência vê o identificador e a data, o emissor, o destinatário, o assunto, a prioridade e o estado, com acesso à Ficha completa. Os botões Novo Expediente, Vídeo-Atendimento e Emissão Documental dão acesso às acções centrais. ",
    "gov-contatos": INTRO + "Está na página Cidadãos, o Quadro de Cadastros Nacionais. Aqui consulta os cidadãos registados na plataforma: para cada um vê o nome e o tipo de conta, o documento de identificação, o contacto, a localidade, a pontuação de correspondência da inteligência artificial e o estado da conta, com os anexos submetidos no registo. Pode rever cadastros pendentes de homologação, aprovar ou rejeitar, criar um aviso geral em campanha para os cidadãos e arquivar contas sintéticas de teste. ",
    "gov-trabalhadores": INTRO + "Está na página Equipa, a Gestão de Equipa do sistema. O Quadro da Equipa lista os colaboradores com o e-mail institucional, o telefone profissional, o perfil funcional e departamento, o estado de acesso e o último acesso. Com Adicionar à Equipa regista um novo membro, e pode editar ou eliminar os existentes. ",
    "gov-emissao": INTRO + "Está na página Emissão, o Correio Oficial da Administração Central. Aqui gere as correspondências enviadas e recebidas pelo administrador, nos separadores Não Lidas, Lidas e Enviadas, e com Nova Mensagem envia comunicações oficiais a cidadãos e instituições. ",
    "gov-docs": INTRO + "Está na página Controle de Emissão Documental. Aqui acompanha as solicitações de documentos digitais dos cidadãos, filtradas por Todos, Emitidos, Pendentes e Rejeitados. Em cada pedido pendente pode Homologar e Emitir o documento, que passa a constar na carteira digital do cidadão com código QR. Os botões Ver Histórico, Notificações e Ver Métricas de Emissão dão acesso ao registo e aos indicadores. ",
    "gov-documentos": INTRO + "Está na página Controle de Emissão Documental. Aqui acompanha as solicitações de documentos digitais dos cidadãos, filtradas por Todos, Emitidos, Pendentes e Rejeitados. Em cada pedido pendente pode Homologar e Emitir o documento, que passa a constar na carteira digital do cidadão com código QR. Os botões Ver Histórico, Notificações e Ver Métricas de Emissão dão acesso ao registo e aos indicadores. ",
    "gov-relatorio": INTRO + "Está na página Relatórios, o Centro de Análise Estratégica. O Resumo Executivo Automático apresenta os indicadores do sistema por área: Correspondências, Instituições, Cidadãos, Equipa, Assistência IA, Documentos Digitais e Auditoria. A Curva de Tendência Mensal mostra a evolução ao longo do ano, com comparação activa e evolução absoluta, e a secção Últimos Trâmites Reais da Caixa Central lista as correspondências mais recentes. Pode exportar o resumo em CSV, gerar Excel, consultar a memória descritiva e imprimir. ",
    "gov-ia": INTRO + "Está na página IA, a Assistência IA Nacional. Aqui vê a arquitectura do assistente nacional, as Instituições com IA activa ou suspensa, as Bases de Conhecimento partilhadas, que pode gerir e sincronizar, e a Monitorização com valores medidos: modelos de IA disponíveis, volume de conversas por sete dias ou mensal e os temas mais consultados. A secção Segurança e Privacidade resume a encriptação, o acesso controlado e a auditoria completa. Os botões Testar IA e Configurar permitem experimentar e ajustar o assistente. ",
    "gov-seguranca": INTRO + "Está na página Auditoria, a Auditoria e Segurança do sistema. No topo, os Alertas Automáticos de Segurança e os indicadores de Segurança Facial, incluindo as tentativas de acesso por biometria. A página organiza-se em Métricas e Tráfego, Modelos de Utilizadores, Registo de Auditoria, com o log completo de acções, e Parâmetros e Consola. Em caso de incidente grave, o botão Activar Protocolo permite a Interrupção de Emergência Cibernética. ",
    "gov-perfil": INTRO + "Está na página Perfil do administrador. No cartão principal encontra o seu nome e a identificação, com os botões Editar Perfil e Mudar Foto. A seguir, as Informações de Conta e a secção Segurança e Credenciais, onde pode alterar a palavra-passe, revelar as credenciais, ver os logs de acesso e registar a sua face para acesso facial. ",
    historico: INTRO + "Está no Centro de Histórico Operacional, a linha do tempo de toda a actividade administrativa: expedientes, solicitações de documentos e notificações. " + HISTORICO_COMUM,
    notificacoes: NOTIFICACOES_COMUM,
    "video-atendimento": INTRO + "Está na página Vídeo-Atendimento da Administração Central. Aqui acompanha os atendimentos por vídeo agendados entre instituições e cidadãos, nos separadores Agenda, Histórico, Calendário e Ajuda, e pode entrar numa sessão a partir do separador Vídeo para fins de supervisão e auditoria. "
  }
};

export function hasPagePresentation(appMode: AppMode, tab: string | undefined): boolean {
  if (!tab) return false;
  const presentations = PAGE_PRESENTATIONS[appMode];
  return !!presentations && (tab in presentations);
}
