/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AppMode } from '../types';

const INTRO = "Seja muito bem-vindo ao Correio Digital Angola. Uma plataforma de correspondência Nacional com o objetivo de unir as Instituições a população. ";

export const PAGE_PRESENTATIONS: Record<AppMode, Record<string, string>> = {
  user: {
    home: INTRO + "Na página Painel, a sua central de comando pessoal. Aqui pode ver todos os seus alertas importantes, documentos recebidos, o estado das suas solicitações e notificações de urgência. O sistema apresenta de forma clara e organizada todas as ações pendentes, documentos pendentes de assinatura e mensagens importantes das instituições. É o ponto de partida para gerir a sua vida digital oficial em Angola. Apresentação terminada.",
    correspondencias: INTRO + "Na página Correio, o seu diálogo direto e oficial com as instituições do Estado. Aqui pode enviar e receber correspondências de forma segura, consultar o histórico de mensagens, acompanhar o estado das suas solicitações e receber notificações em tempo real. Todas as comunicações são encriptadas e autenticadas, garantindo que apenas você e a instituição destinatária têm acesso ao conteúdo. Apresentação terminada.",
    contatos: INTRO + "Na página Contactos, a sua lista de pessoas de confiança para situações de emergência. Esta funcionalidade permite adicionar contactos de familiares, amigos próximos ou vizinhos que podem ser contactados rapidamente em caso de acidente, emergência médica ou quando uma instituição está a tentar contactar consigo com urgência e não consegue. Pode adicionar até cinco contactos de emergência, definir relações como familiar, amigo ou vizinho, e incluir números de telefone alternativos. Apresentação terminada.",
    contactos: INTRO + "Na página Contactos, a sua lista de pessoas de confiança para situações de emergência. Esta funcionalidade permite adicionar contactos de familiares, amigos próximos ou vizinhos que podem ser contactados rapidamente em caso de acidente, emergência médica ou quando uma instituição está a tentar contactar consigo com urgência e não consegue. Pode adicionar até cinco contactos de emergência, definir relações como familiar, amigo ou vizinho, e incluir números de telefone alternativos. Apresentação terminada.",
    perfil: INTRO + "Na página Conta, onde encontrará todas as suas informações pessoais e configurações de segurança. Aqui pode gerir os seus dados biométricos, verificar o seu Bilhete de Identidade digital, alterar preferências de idioma entre Português e dialetos angolanos, configurar notificações push, gerir a sua privacidade e segurança da conta. É também onde pode visualizar o histórico de acessos e atividades na sua conta. Apresentação terminada.",
    "video-atendimento": INTRO + "Na página VideoAtendimento, a ferramenta de videochamada para atendimento remoto de cidadãos. Aqui pode agendar sessões de videochamada com funcionários de instituições, ter atendimento por vídeo em tempo real, partilhar documentos durante a chamada e gravar sessões para fins de qualidade e auditoria. O sistema usa tecnologia Jitsi para garantir videochamadas seguras e de alta qualidade. Funciona no navegador sem necessidade de instalar aplicações adicionais. Apresentação terminada."
  },
  institution: {
    home: INTRO + "Na página Painel, o dashboard institucional da sua organização. Aqui pode visualizar métricas de atendimento, número de cidadãos atendidos, documentos emitidos, tempo médio de resposta e estado dos serviços. O painel apresenta gráficos em tempo real com indicadores de desempenho, alertas de serviços em manutenção e notificações importantes para a gestão institucional. Apresentação terminada.",
    correspondencias: INTRO + "Na página Correio, o sistema de correspondência institucional. Aqui pode gerir todas as comunicações oficiais da sua instituição, enviar documentos aos cidadãos, receber e processar pedidos, criar protocolos de resposta rápida e gerir a fila de atendimento. O sistema permite organizar as mensagens por categoria, urgência e estado de processamento. Apresentação terminada.",
    "gov-contatos": INTRO + "Na página Equipa, onde encontrará a gestão de funcionários da sua instituição. Aqui pode adicionar, editar e remover membros da equipa autorizados a usar a plataforma, definir permissões e níveis de acesso, visualizar quem está online no momento e gerir a agenda de atendimento de cada colaborador. É essencial para manter a segurança e organização da equipa. Apresentação terminada.",
    "inst-qrcode": INTRO + "Na página QR Code, a ferramenta de validação de documentos digitais. Quando um cidadão apresentar um documento com código QR, utilize esta funcionalidade para localizar rapidamente o documento no sistema. Basta digitalizar ou inserir o código QR para aceder instantaneamente ao documento, verificar a sua autenticidade, consultar o histórico de validações anteriores e confirmar a identidade do titular. Esta ferramenta é essencial para garantir que apenas documentos legítimos e atualizados são aceites pela sua instituição. Apresentação terminada.",
    "inst-ai-assistant": INTRO + "Na página IA, o assistente de inteligência artificial configurado especificamente para a sua instituição. Aqui pode adicionar arquivos à base de conhecimento para que a IA responda com informações atualizadas sobre os serviços da sua instituição, definir instruções personalizadas que guiam o comportamento da IA nas conversas com os cidadãos, configurar respostas automáticas para perguntas frequentes e treinar a IA com documentos oficiais e procedimentos internos. A IA está integrada com os procedimentos e diretrizes específicas da sua organização. Apresentação terminada.",
    perfil: INTRO + "Na página Conta, onde encontrará as configurações da conta institucional. Aqui pode gerir o perfil da instituição, atualizar informações de contacto, configurar horário de funcionamento, definir serviços disponíveis, gerir notificações para a equipa e acessar relatórios de uso da plataforma pela sua organização. Apresentação terminada.",
    "video-atendimento": INTRO + "Na página VideoAtendimento, a ferramenta de videochamada para atendimento remoto de cidadãos. Aqui pode agendar sessões de videochamada com funcionários de instituições, ter atendimento por vídeo em tempo real, partilhar documentos durante a chamada e gravar sessões para fins de qualidade e auditoria. O sistema usa tecnologia Jitsi para garantir videochamadas seguras e de alta qualidade. Funciona no navegador sem necessidade de instalar aplicações adicionais. Apresentação terminada."
  },
  admin: {
    "gov-dashboard": INTRO + "Na página Painel, o centro de operações integrado do Sistema de Operações Central. Aqui pode visualizar indicadores-chave de desempenho nacional em tempo real, incluindo número de cidadãos registrados, documentos emitidos, mensagens processadas e estado de todas as instituições federadas. O painel apresenta um mapa interativo de Angola com indicadores por província, alertas críticos de segurança e métricas de desempenho do sistema nacional. Apresentação terminada.",
    "gov-interoperabilidade": INTRO + "Na página Instituições, onde encontrará a gestão centralizada de todas as instituições federadas ao sistema. Aqui pode adicionar novas instituições ao ecossistema, configurar integrações com sistemas existentes, definir regras de interoperabilidade, monitorar disponibilidade de serviços, gerir credenciais de API e visualizar o estado de cada instituição em tempo real. É o painel de controlo da rede nacional de atendimento. Apresentação terminada.",
    "gov-correspondencias": INTRO + "Na página Correspondências, onde encontrará o registo consolidado de todas as mensagens do sistema. Aqui pode visualizar cada correspondência enviada ou recebida por qualquer instituição, pesquisar por cidadão, instituição, data ou tipo de documento, acompanhar o fluxo completo de cada mensagem desde o envio até a receção e gerar relatórios de tráfego de correspondências. É o centro de monitorização da comunicação oficial nacional. Apresentação terminada.",
    "gov-contatos": INTRO + "Na página Cidadãos, onde encontrará a base de dados de todos os cidadãos registrados no systema. Aqui pode visualizar perfis de cidadãos, histórico de interações com instituições, estado de documentos, alertas de urgência pendentes e informações de contacto em caso de emergência. O sistema permite também identificar cidadãos que não estão a receber correspondências e tomar medidas corretivas. Apresentação terminada.",
    "gov-trabalhadores": INTRO + "Na página Equipa, onde encontrará a gestão de todos os funcionários de todas as instituições. Aqui pode ter uma visão consolidada de quem está a trabalhar no sistema, níveis de acesso por instituição, atividade recente de cada colaborador e permissões especiais. É essencial para auditoria e segurança do sistema nacional. Apresentação terminada.",
    "gov-relatorio": INTRO + "Na página Relatórios, onde encontrará ferramentas de análise e relatórios consolidados. Aqui pode gerar relatórios de desempenho por instituição, análise de volume de documentos emitidos, métricas de satisfação de cidadãos, relatórios de conformidade regulatória e exportação de dados para análise externa. Os relatórios podem ser gerados em formato PDF ou CSV para arquivo. Apresentação terminada.",
    "gov-ia": INTRO + "Na página IA, o painel de controlo do sistema de inteligência artificial nacional. Aqui pode monitorar o desempenho dos modelos de IA em uso, adicionar arquivos às bases de conhecimento para que todas as instituições tenham acesso a informações consolidadas, dar instruções globais que são aplicadas a todos os assistentes de IA do sistema, gerir bases de conhecimento vetorizadas, visualizar estatísticas de conversas atendidas pela IA, ajustar modelos padrão, configurar comportamentos por instituição e testar novas configurações antes de implementar. É o centro de comando da inteligência artificial do sistema. Apresentação terminada.",
    "gov-seguranca": INTRO + "Na página Auditoria, onde encontrará o registo completo e detalhado de todas as ações no sistema. Aqui pode visualizar logs de acesso, transações de documentos, tentativas de autenticação, alterações de configurações e qualquer atividade suspeita. É essencial para garantir a segurança do sistema e investigar incidentes. Todos os logs são protegidos contra alteração e mantidos pelo período legal obrigatório. Apresentação terminada.",
    "gov-perfil": INTRO + "Na página Conta, onde encontrará as configurações do perfil de administrador do sistema. Aqui pode gerir a sua identidade como administrador central, configurar autenticação de dois fatores, gerir sessões ativas, configurar notificações pessoais e acessar configurações avançadas do sistema SOC. Apresentação terminada.",
    "video-atendimento": INTRO + "Na página VideoAtendimento, a ferramenta de videochamada para atendimento remoto de cidadãos. Aqui pode agendar sessões de videochamada com funcionários de instituições, ter atendimento por vídeo em tempo real, partilhar documentos durante a chamada e gravar sessões para fins de qualidade e auditoria. O sistema usa tecnologia Jitsi para garantir videochamadas seguras e de alta qualidade. Funciona no navegador sem necessidade de instalar aplicações adicionais. Apresentação terminada."
  }
};

export function hasPagePresentation(appMode: AppMode, tab: string | undefined): boolean {
  if (!tab) return false;
  const presentations = PAGE_PRESENTATIONS[appMode];
  return !!presentations && (tab in presentations);
}
