import assert from 'node:assert/strict';
import {contarNotificacoesAtalhos as count} from '../../src/utils/notificacoesAtalhos';
const n=(id:number,targetTab:string,title='',unread=true,message='')=>({id,targetTab,title,unread,message,time:'Agora',type:'info' as const});
const m=(id:number,subject:string,unread=1,extra={})=>({id,details:{subject},unread,...extra} as any);
let checks=0;
assert.deepEqual(count([],[],false),{'video-atendimento':0,inqueritos:0,ocorrencias:0,denuncias:0});checks++;
assert.equal(count([n(1,'video-atendimento')],[],false)['video-atendimento'],1);checks++;
assert.equal(count([n(1,'video-atendimento','',false)],[],false)['video-atendimento'],0);checks++;
assert.equal(count([n(1,'inst-video')],[],true)['video-atendimento'],1);checks++;
assert.equal(count([n(1,'video-atendimento'),n(1,'video-atendimento')],[],false)['video-atendimento'],1);checks++;
assert.equal(count([n(1,'correspondencias','Denúncia — Em análise')],[],false).denuncias,1);checks++;
assert.equal(count([], [m(1,'[DENÚNCIA] Teste')], false).denuncias,0);checks++;
assert.equal(count([], [m(1,'[DENÚNCIA] Teste')], true).denuncias,1);checks++;
assert.equal(count([], [m(1,'Consulta de teste',1,{sondagem_id:'x'})], false).inqueritos,1);checks++;
assert.equal(count([], [m(1,'Consulta de teste',0,{sondagem_id:'x'})], false).inqueritos,0);checks++;
assert.equal(count([], [m(1,'Consulta de teste',1,{sondagem_id:'x'})], true).inqueritos,0);checks++;
assert.equal(count([n(1,'correspondencias','Nova mensagem',true,'Consulta de teste')], [m(1,'Consulta de teste',1,{sondagem_id:'x'})], false).inqueritos,1);checks++;
assert.equal(count([n(1,'sondagens','Nova resposta')],[],true).inqueritos,1);checks++;
assert.equal(count([],[],false,12).ocorrencias,12);checks++;
assert.equal(count([n(1,'home','Mensagem normal')],[],false).denuncias,0);checks++;
console.log(`${checks} verificações de contagem aprovadas.`);
